server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow
    username: workflow
    password: workflow
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health

workflow:
  recovery:
    enabled: true
    interval-ms: 2000

springdoc:
  paths-to-match: /api/**
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
  api-docs:
    path: /v3/api-docs
